# Generated by Django 4.0.1 on 2022-01-20 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_recomender', '0002_person_foodproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
        migrations.AddField(
            model_name='person',
            name='categories',
            field=models.ManyToManyField(to='food_recomender.Category'),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_recomender.category'),
        ),
    ]
